title: Leandro Russo
logo: https://avatars.githubusercontent.com/u/124142011?v=4
#description: Text below the image
#show_download: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
